spring.application.name=CotSys
spring.datasource.url=jdbc:postgresql://localhost:5432/cotsysdbfinal
spring.datasource.username=postgres
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
logging.level.org.hibernate.SQL=ERROR
logging.level.com.innosistemas=DEBUG    
logging.level.org.springframework.security=DEBUG

# JWT Configuration
app.jwtSecret=b73c2ab450d1f9e692c0327381632842f458d430da6c19d071bd7df4e913db70
app.jwtExpirationMs=86400000
app.jwtExpirationRefresh=604800000
